#!/usr/bin/env python3
"""
Get Real YouTube Cookies
Bu script, browser'dan gerçek YouTube cookies'ini almak için yardımcı olur.
"""

import os
import sys
import subprocess
import webbrowser

def install_browser_cookie3():
    """Install browser-cookie3 package"""
    print("📦 Installing browser-cookie3...")
    try:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "browser-cookie3"])
        print("✅ browser-cookie3 installed successfully")
        return True
    except Exception as e:
        print(f"❌ Failed to install browser-cookie3: {e}")
        return False

def get_chrome_cookies():
    """Get cookies from Chrome browser"""
    print("🍪 Getting cookies from Chrome...")
    try:
        import browser_cookie3
        
        # Get YouTube cookies from Chrome
        cookies = browser_cookie3.chrome(domain_name='.youtube.com')
        
        if not cookies:
            print("❌ No YouTube cookies found in Chrome")
            print("   Please make sure you're logged into YouTube in Chrome")
            return False
        
        # Convert to Netscape format
        with open('cookies.txt', 'w', encoding='utf-8') as f:
            f.write('# Netscape HTTP Cookie File\n')
            f.write('# This file was generated by get_real_cookies.py\n')
            f.write('# Please do not edit this file manually.\n\n')
            
            for cookie in cookies:
                # Netscape format: domain, domain_specified, path, secure, expires, name, value
                domain = cookie.domain
                domain_specified = 'TRUE' if domain.startswith('.') else 'FALSE'
                path = cookie.path or '/'
                secure = 'TRUE' if cookie.secure else 'FALSE'
                expires = cookie.expires or 0
                name = cookie.name
                value = cookie.value
                
                f.write(f'{domain}\t{domain_specified}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n')
        
        print(f"✅ Found {len(list(cookies))} YouTube cookies")
        print("✅ Cookies saved to cookies.txt")
        return True
        
    except ImportError:
        print("❌ browser-cookie3 not installed")
        return False
    except Exception as e:
        print(f"❌ Error getting cookies: {e}")
        return False

def get_firefox_cookies():
    """Get cookies from Firefox browser"""
    print("🍪 Getting cookies from Firefox...")
    try:
        import browser_cookie3
        
        # Get YouTube cookies from Firefox
        cookies = browser_cookie3.firefox(domain_name='.youtube.com')
        
        if not cookies:
            print("❌ No YouTube cookies found in Firefox")
            print("   Please make sure you're logged into YouTube in Firefox")
            return False
        
        # Convert to Netscape format
        with open('cookies.txt', 'w', encoding='utf-8') as f:
            f.write('# Netscape HTTP Cookie File\n')
            f.write('# This file was generated by get_real_cookies.py\n')
            f.write('# Please do not edit this file manually.\n\n')
            
            for cookie in cookies:
                domain = cookie.domain
                domain_specified = 'TRUE' if domain.startswith('.') else 'FALSE'
                path = cookie.path or '/'
                secure = 'TRUE' if cookie.secure else 'FALSE'
                expires = cookie.expires or 0
                name = cookie.name
                value = cookie.value
                
                f.write(f'{domain}\t{domain_specified}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n')
        
        print(f"✅ Found {len(list(cookies))} YouTube cookies")
        print("✅ Cookies saved to cookies.txt")
        return True
        
    except ImportError:
        print("❌ browser-cookie3 not installed")
        return False
    except Exception as e:
        print(f"❌ Error getting cookies: {e}")
        return False

def manual_cookies_guide():
    """Show manual cookies guide"""
    print("\n📋 Manual Cookies Guide:")
    print("=" * 40)
    print("1. Open Chrome/Firefox")
    print("2. Go to https://www.youtube.com")
    print("3. Make sure you're logged in")
    print("4. Press F12 to open Developer Tools")
    print("5. Go to Application/Storage tab")
    print("6. Find Cookies > https://www.youtube.com")
    print("7. Copy all cookies")
    print("8. Save as cookies.txt in Netscape format")
    print("\n📝 Netscape format example:")
    print(".youtube.com\tTRUE\t/\tFALSE\t1735689600\tVISITOR_INFO1_LIVE\tyour_value_here")
    print(".youtube.com\tTRUE\t/\tFALSE\t1735689600\tLOGIN_INFO\tyour_value_here")

def open_youtube():
    """Open YouTube in browser"""
    print("🌐 Opening YouTube...")
    try:
        webbrowser.open('https://www.youtube.com')
        print("✅ YouTube opened in browser")
        print("   Please log in to your Google account")
        return True
    except Exception as e:
        print(f"❌ Failed to open YouTube: {e}")
        return False

def main():
    """Main function"""
    print("🍪 YouTube Cookies Getter")
    print("=" * 30)
    
    # Check if cookies.txt already exists
    if os.path.exists('cookies.txt'):
        print("⚠️  cookies.txt already exists")
        response = input("Do you want to overwrite it? (y/n): ")
        if response.lower() != 'y':
            print("❌ Operation cancelled")
            return
    
    # Install browser-cookie3 if needed
    try:
        import browser_cookie3
        print("✅ browser-cookie3 already installed")
    except ImportError:
        if not install_browser_cookie3():
            print("❌ Cannot proceed without browser-cookie3")
            return
    
    # Try to get cookies
    print("\n🔍 Trying to get cookies automatically...")
    
    # Try Chrome first
    if get_chrome_cookies():
        print("✅ Successfully got cookies from Chrome!")
        return
    
    # Try Firefox if Chrome failed
    if get_firefox_cookies():
        print("✅ Successfully got cookies from Firefox!")
        return
    
    # If both failed, show manual guide
    print("\n❌ Could not get cookies automatically")
    print("   This might be due to browser security settings")
    
    # Open YouTube for manual process
    open_youtube()
    manual_cookies_guide()
    
    print("\n📋 After getting cookies manually:")
    print("1. Save as cookies.txt in project folder")
    print("2. Restart API: python api_server.py")
    print("3. Test: curl 'http://localhost:5000/api/search?q=test&limit=3'")

if __name__ == "__main__":
    main() 